apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    server: https://192.168.49.2:8443
    insecure-skip-tls-verify: true
contexts:
- name: client-context
  context:
    cluster: minikube
    user: client
current-context: client-context
users:
- name: client
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InlEWHR0VXNSb3RiQjcwdDZ2eWJnVzhSMXRIUFl6TnM3d1Nva2FRTWNxZVEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ0NzE4NzQ4LCJpYXQiOjE3NDQ3MTUxNDgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiOWYwMmM1MGYtMDhhYS00YTk0LWJjOGYtNDE5YmIyM2Y5NjM4Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImNsaWVudC1zYSIsInVpZCI6IjU0ZjQyNWVmLTcwYzAtNDM4Ny1iMDhmLTQ0MDNhYjA5NTU3MCJ9fSwibmJmIjoxNzQ0NzE1MTQ4LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpjbGllbnQtc2EifQ.ihMX3gCYtn2pyjB8bN5jiNQjh1Y2nMxutjRC_EGbFt0HaTQ0H84z_cNLMKgSMNYR3ib8dqdlWGYa3gXcjqv_kGxUnN8ZfsCrQtMkrxpiAvnv8pmJRU0_rNyHyzNi5Kik20DEgO5a_KCk-PR0hRvf16MY_EUXqH9wz1nFdd5Ft85GIb3QUo2hpiI7DTfgYlVn_vfIbn_9_tGf067aymBGI1p5YrdaLKw1ep6QC38Yho5ndxLmGGGQ4x24lWiH8BIEJcrX8hColI9gL0it7WGVWwXnsbjEagq2N9kY5MGt49a18ZQl1OLwPoMt6vVR-WLkuqNfgzinGHvAwcoFXZX6tw
