apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: handmadeglow-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: handmadeglow-sa
  namespace: default
roleRef:
  kind: Role
  name: handmadeglow-role
  apiGroup: rbac.authorization.k8s.io
