apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # or wherever the app is deployed
  name: handmadeglow-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
