apiVersion: v1
kind: Service
metadata:
  name: handmadeglow-service
spec:
  selector:
    app: handmadeglow
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080