apiVersion: v1
kind: Service
metadata:
  name: emperia-service
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
      nodePort: 30808
  type: NodePort
  selector:
    app: emperia