apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: emperia-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: emperia-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - emperia-gateway
  http:
    - match:
        - uri:
            prefix: /emperia/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: emperia-service.default.svc.cluster.local
