version: '3.8'

services:
  db:
    image: postgres:14.5-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=emperia
      - POSTGRES_PASSWORD=pass_emperia
      - POSTGRES_DB=handmadeglow
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: