apiVersion: v1
kind: ServiceAccount
metadata:
  name: superadmin-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-sa
  namespace: default