apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: superadmin-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: superadmin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: superadmin-role
subjects:
- kind: ServiceAccount
  name: superadmin-sa
  namespace: default
